name: Build container
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".devcontainer/Dockerfile"
      - ".github/workflows/build.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  LOCATION: simonhyll
  IMAGE_NAME: devcontainer-tauri-android
jobs:
  build_deploy:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Log in to the Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3.1.0

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.LOCATION }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=true
      - run: sudo rm -rf /usr/local/lib/android
      - run: sudo rm -rf /usr/share/dotnet
      - run: sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .devcontainer/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=min
